### ISSUE TITLE
Implement Light and Dark Theme Support for ScoutGame

### ISSUE THREAD

**Issue by metanodreamer** [etherion-tools/ScoutLens#4]
**Description:**  
To improve user experience and accessibility, ScoutLens should support both light and dark theme options that users can toggle within the extension.

**Tasks:**  
- **CSS Overrides:**  
  - Identify key CSS classes and IDs used by ScoutGame’s UI (cards, background, buttons, text).
  - Create two CSS files: one for a light theme and one for a dark theme, overriding the relevant styles.
- **Theme Injection:**  
  - Modify the extension to inject the appropriate CSS file based on user selection.
- **User Interface:**  
  - Add a settings panel or toggle button within the extension popup to allow users to switch between themes.
- **Testing:**  
  - Test the themes on all major ScoutGame pages to ensure UI consistency and no interference with existing features.

**Example CSS Snippets:**  
```css
/* Light Theme */
body { background: #f5f5f5; color: #212121; }
.card { background: #fff; border: 1px solid #ddd; }
button { background: #6200EE; color: #fff; }

/* Dark Theme */
body { background: #121212; color: #e0e0e0; }
.card { background: #1e1e1e; border: 1px solid #333; }
button { background: #3700B3; color: #fff; }
```
